// app/layout.tsx
import "~/styles/globals.css";

import { Geist } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { auth } from "~/server/auth";
import { type Metadata } from "next";
import Navbar from "~/components/main/Navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en" className={geist.variable}>
      <body className="bg-[#242424] h-screen">
        {!session?.user.preferences ? (
          <>
          {/* Signed out navbar */}
          </>
        ) : (
          <>
            <Navbar />
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </>
        )}
      </body>
    </html>
  );
}
