// app/layout.tsx
import "~/styles/globals.css";

import { Geist } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { auth } from "~/server/auth";
import { type Metadata } from "next";
import Navbar from "~/components/main/Navbar";
import { ThemeProvider } from "~/components/main/ThemeProvider";
import { ProviderWrapper } from "~/components/main/ProviderWrapper";
import { SessionProvider } from "next-auth/react";
import { HydrateClient } from "~/trpc/server";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en" className={geist.variable} suppressHydrationWarning>
      <body className="dark:bg-[#242424] bg-white h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>
            <HydrateClient>
              <ProviderWrapper session={session}>
                <Navbar />
                {children}
              </ProviderWrapper>
            </HydrateClient>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
